# Generated by Django 6.0.7 on 2026-07-29 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('6E', '6ème'), ('5E', '5ème'), ('4E', '4ème'), ('3E', '3ème'), ('2NDA', '2nde A'), ('2NDC', '2nde C'), ('1REA', '1ère A'), ('1REC', '1ère C'), ('1RED', '1ère D'), ('TLEA', 'Terminale A'), ('TLEC', 'Terminale C'), ('TLED', 'Terminale D')], max_length=6)),
                ('version', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True, help_text='Une seule version active par école et par niveau.')),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix réduit du kit, en F CFA.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits_crees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(limit_choices_to={'type': 'ECOLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='core.site')),
            ],
            options={
                'verbose_name': 'kit scolaire',
                'ordering': ['ecole__nom', 'niveau', '-version'],
            },
        ),
        migrations.CreateModel(
            name='KitLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='kits.kit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_kit', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'ligne de kit',
                'ordering': ['produit__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='kit',
            constraint=models.UniqueConstraint(fields=('ecole', 'niveau', 'version'), name='une_version_par_ecole_et_niveau'),
        ),
        migrations.AddConstraint(
            model_name='kit',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('ecole', 'niveau'), name='un_seul_kit_actif_par_ecole_et_niveau'),
        ),
        migrations.AddConstraint(
            model_name='kitligne',
            constraint=models.UniqueConstraint(fields=('kit', 'produit'), name='un_produit_une_fois_par_kit'),
        ),
    ]
