# Generated by Django 6.0.7 on 2026-08-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0002_classeecole_kit_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='actif',
            field=models.BooleanField(default=True, help_text='Une seule version active par classe.'),
        ),
    ]
