# Generated by Django 6.0.7 on 2026-07-29 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_sequencecompteur_site_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'catégorie de dépense',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('motif', models.CharField(max_length=500)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=12)),
                ('date_depense', models.DateField(help_text='Date effective de la dépense.')),
                ('piece_justificative', models.CharField(blank=True, help_text='Référence ou description du justificatif.', max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.CharField(blank=True, max_length=500)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='depenses.categoriedepense')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dépense',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['site', 'date_depense'], name='depenses_de_site_id_392710_idx')],
            },
        ),
    ]
