# Generated by Django 6.0.7 on 2026-08-15 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_versement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='versement',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versement',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT_BANQUE', 'Virement bancaire')], max_length=15),
        ),
    ]
