# Generated by Django 6.0.7 on 2026-08-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_numero_local'),
        ('depenses', '0003_versement_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.site'),
        ),
    ]
