# Generated by Django 6.0.7 on 2026-08-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_depense_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='recu_banque',
            field=models.ImageField(blank=True, null=True, upload_to='versements/recus/'),
        ),
    ]
