# Generated by Django 6.0.7 on 2026-07-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE_ACHAT', 'Entrée — réception fournisseur'), ('ENTREE_TRANSFERT', 'Entrée — transfert reçu'), ('SORTIE_VENTE', 'Sortie — vente'), ('SORTIE_TRANSFERT', 'Sortie — transfert émis'), ('PERTE', 'Sortie — perte ou casse'), ('AJUSTEMENT', "Ajustement d'inventaire"), ('ANNULATION', "Mouvement compensatoire d'annulation")], max_length=20)),
                ('quantite', models.IntegerField(help_text='Signée : positive pour une entrée, négative pour une sortie.')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference_document', models.CharField(blank=True, help_text="Numéro de vente, de transfert ou d'inventaire à l'origine du mouvement.", max_length=100)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='catalogue.produit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.site')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['site', 'produit', 'horodatage'], name='stock_mouve_site_id_334eb0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantite', 0), _negated=True), name='mouvement_non_nul')],
            },
        ),
        migrations.CreateModel(
            name='SoldeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, help_text="Somme des mouvements. Peut être négatif : c'est une alerte, pas un bug.")),
                ('stock_securite', models.PositiveIntegerField(default=0, help_text='Seuil déclenchant le réapprovisionnement.')),
                ('stock_maximum', models.PositiveIntegerField(default=0, help_text='Plafond au-delà duquel on ne commande plus.')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldes', to='catalogue.produit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldes', to='core.site')),
            ],
            options={
                'verbose_name': 'solde de stock',
                'ordering': ['site', 'produit'],
                'constraints': [models.UniqueConstraint(fields=('site', 'produit'), name='un_solde_par_site_et_produit')],
            },
        ),
    ]
