# Generated by Django 6.0.7 on 2026-07-29 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0006_sequencecompteur_site_code'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=12)),
                ('motif', models.CharField(help_text="Raison de l'ajustement : perte, casse, correction d'écart...", max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_crees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='core.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ajustement de stock',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='AjustementLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(help_text='Signée : positive = entrée, négative = sortie/perte.')),
                ('ajustement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.ajustement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='catalogue.produit')),
            ],
            options={
                'verbose_name': "ligne d'ajustement",
                'constraints': [models.UniqueConstraint(fields=('ajustement', 'produit'), name='un_produit_par_ajustement')],
            },
        ),
    ]
