# Generated by Django 6.0.7 on 2026-07-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_mouvementstock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldestock',
            name='stock_minimum',
            field=models.PositiveIntegerField(default=0, help_text='Quantité minimale absolue à maintenir.'),
        ),
    ]
