# Generated by Django 6.0.7 on 2026-08-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_solde_stock_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('ENTREE_ACHAT', 'Entrée — réception fournisseur'), ('ENTREE_TRANSFERT', 'Entrée — transfert reçu'), ('SORTIE_VENTE', 'Sortie — vente'), ('SORTIE_TRANSFERT', 'Sortie — transfert émis'), ('PERTE', 'Sortie — perte ou casse'), ('AJUSTEMENT', "Ajustement d'inventaire"), ('ANNULATION', "Mouvement compensatoire d'annulation"), ('SORTIE_LIVRAISON_ECOLE', 'Sortie — livraison école (stock réservé)'), ('ENTREE_LIVRAISON_ECOLE', 'Entrée — livraison reçue du magasin'), ('RETOUR_LIVRAISON_ECOLE', 'Retour — réception partielle'), ('SORTIE_APPRO_MAGASIN', 'Sortie — expédition vers magasin'), ('ENTREE_APPRO_MAGASIN', 'Entrée — réception depuis dépôt')], max_length=30),
        ),
    ]
