# Generated by Django 6.0.7 on 2026-07-29 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0006_sequencecompteur_site_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('site_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to='core.site')),
                ('site_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_emis', to='core.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transfert',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='TransfertLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_transfert', to='catalogue.produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transferts.transfert')),
            ],
            options={
                'verbose_name': 'ligne de transfert',
            },
        ),
        migrations.AddConstraint(
            model_name='transfert',
            constraint=models.CheckConstraint(condition=models.Q(('site_origine', models.F('site_destination')), _negated=True), name='transfert_origine_destination_differents'),
        ),
        migrations.AddConstraint(
            model_name='transfertligne',
            constraint=models.UniqueConstraint(fields=('transfert', 'produit'), name='un_produit_par_transfert'),
        ),
    ]
