# Generated by Django 6.0.7 on 2026-08-08 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='valide_le',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='valide_par',
        ),
        migrations.AddField(
            model_name='transfert',
            name='traite_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfert',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=12),
        ),
    ]
