# Generated by Django 6.0.7 on 2026-08-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transfert_type_don_surplus'),
        ('transferts', '0002_statuts_et_traitement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfert',
            name='transfert_origine_destination_differents',
        ),
        migrations.AddField(
            model_name='transfert',
            name='type_transfert',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DON', 'Don'), ('SURPLUS', 'Surplus')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='site_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to='core.site'),
        ),
        migrations.AddConstraint(
            model_name='transfert',
            constraint=models.CheckConstraint(condition=models.Q(('site_destination__isnull', True), models.Q(('site_origine', models.F('site_destination')), _negated=True), _connector='OR'), name='transfert_origine_destination_differents'),
        ),
    ]
