# Generated by Django 6.0.7 on 2026-07-29 15:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'zone',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAGASIN', 'Magasin'), ('ECOLE', 'École')], max_length=10)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('remise_convention', models.DecimalField(decimal_places=2, default=0, help_text="Remise en %, accordée au personnel administratif de l'établissement.", max_digits=5)),
                ('magasin_rattachement', models.ForeignKey(blank=True, help_text='Magasin qui approvisionne cette école.', limit_choices_to={'type': 'MAGASIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecoles_approvisionnees', to='core.site')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.zone')),
            ],
            options={
                'verbose_name': 'site',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profil', models.CharField(choices=[('DG', 'Directeur Général'), ('MANAGER', 'Manager Général'), ('SUPERVISEUR', 'Superviseur de zone'), ('GEST_MAGASIN', 'Gestionnaire de magasin'), ('CHEF_EQUIPE', "Chef d'équipe"), ('COMMERCIAL', 'Commercial / Caissière')], default='COMMERCIAL', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('site', models.ForeignKey(blank=True, help_text='Site de rattachement : école pour un commercial, magasin pour un gestionnaire.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.site')),
                ('zone', models.ForeignKey(blank=True, help_text='Périmètre du superviseur de zone.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.zone')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('type', 'nom'), name='site_nom_unique_par_type'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'ECOLE'), ('magasin_rattachement__isnull', True), _connector='OR'), name='seule_une_ecole_a_un_magasin_de_rattachement'),
        ),
    ]
