# Generated by Django 6.0.7 on 2026-07-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supprimer_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCompteur',
            fields=[
                ('cle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valeur', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'compteur de séquence',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, help_text='Code court pour les numéros de documents (ex. MFB pour Mamie Fétaï Bingerville).', max_length=10),
        ),
    ]
