# Generated by Django 6.0.7 on 2026-07-29 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sequencecompteur_site_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('INFO', 'Information')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'lue', '-cree_le'], name='core_notifi_destina_5e64e6_idx')],
            },
        ),
    ]
