# Generated by Django 6.0.7 on 2026-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('LIVRAISON_PRETE', 'Livraison prête à réceptionner'), ('INFO', 'Information')], max_length=20),
        ),
    ]
