# Generated by Django 6.0.7 on 2026-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('DEPOT', 'Dépôt général'), ('MAGASIN', 'Magasin'), ('ECOLE', 'École')], max_length=10),
        ),
    ]
