# Generated by Django 6.0.7 on 2026-08-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='groupe',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEMANDE_REJETEE', "Demande d'achat rejetée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('LIVRAISON_PRETE', 'Livraison prête à réceptionner'), ('LIVRAISON_CONFIRMEE', 'Livraison confirmée'), ('LIVRAISON_REFUSEE', 'Livraison refusée'), ('INFO', 'Information')], max_length=20),
        ),
    ]
