# Generated by Django 6.0.7 on 2026-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEMANDE_REJETEE', "Demande d'achat rejetée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('LIVRAISON_PRETE', 'Livraison prête à réceptionner'), ('LIVRAISON_CONFIRMEE', 'Livraison confirmée'), ('LIVRAISON_REFUSEE', 'Livraison refusée'), ('INFO', 'Information'), ('NON_CONFORMITE', 'Non-conformité signalée')], max_length=20),
        ),
    ]
