# Generated by Django 6.0.7 on 2026-08-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_derniere_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEMANDE_REJETEE', "Demande d'achat rejetée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('TRANSFERT_RECU', 'Transfert reçu'), ('TRANSFERT_ACCEPTE', 'Transfert accepté'), ('TRANSFERT_REJETE', 'Transfert rejeté'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('LIVRAISON_PRETE', 'Livraison prête à réceptionner'), ('LIVRAISON_CONFIRMEE', 'Livraison confirmée'), ('LIVRAISON_REFUSEE', 'Livraison refusée'), ('INFO', 'Information'), ('NON_CONFORMITE', 'Non-conformité signalée')], max_length=20),
        ),
    ]
