# Generated by Django 6.0.7 on 2026-08-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_type_demande_annulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RUPTURE_STOCK', 'Rupture de stock'), ('DEMANDE_SOUMISE', "Demande d'achat soumise"), ('DEMANDE_VALIDEE', "Demande d'achat validée"), ('DEMANDE_REJETEE', "Demande d'achat rejetée"), ('DEPENSE_SOUMISE', 'Dépense soumise'), ('DEPENSE_VALIDEE', 'Dépense validée'), ('DEPENSE_REJETEE', 'Dépense rejetée'), ('TRANSFERT_RECU', 'Transfert reçu'), ('TRANSFERT_ACCEPTE', 'Transfert accepté'), ('TRANSFERT_REJETE', 'Transfert rejeté'), ('TRANSFERT_VALIDE', 'Transfert validé'), ('INVENTAIRE_VALIDE', 'Inventaire validé'), ('VENTE_ANNULEE', 'Vente annulée'), ('DEMANDE_ANNULATION', "Demande d'annulation de vente"), ('ANNULATION_REJETEE', "Demande d'annulation rejetée"), ('LIVRAISON_PRETE', 'Livraison prête à réceptionner'), ('LIVRAISON_CONFIRMEE', 'Livraison confirmée'), ('LIVRAISON_REFUSEE', 'Livraison refusée'), ('VERSEMENT_RECU', 'Versement reçu à approuver'), ('VERSEMENT_CONFIRME', 'Versement confirmé'), ('VERSEMENT_REJETE', 'Versement rejeté'), ('INFO', 'Information'), ('NON_CONFORMITE', 'Non-conformité signalée')], max_length=20),
        ),
    ]
