# Generated by Django 6.0.7 on 2026-08-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_simplifier_structure_famien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['nom'], 'verbose_name': 'site'},
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, help_text='Code court pour les numéros de documents (ex. SIT01).', max_length=10),
        ),
        migrations.AlterField(
            model_name='site',
            name='remise_convention',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remise en %, accordée au personnel administratif.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('SITE', 'Site')], default='SITE', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('CHEF_EQUIPE', "Chef d'équipe")], default='CHEF_EQUIPE', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='site',
            field=models.ForeignKey(blank=True, help_text="Site de rattachement (obligatoire pour un chef d'équipe).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.site'),
        ),
    ]
