# Generated by Django 6.0.7 on 2026-07-29 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0006_sequencecompteur_site_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE_N1', 'Validé superviseur'), ('VALIDE', 'Validé DG'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('valide_n1_le', models.DateTimeField(blank=True, null=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.CharField(blank=True, max_length=500)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat_creees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_achat', to='core.site')),
                ('valide_n1_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_validees_n1', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "demande d'achat",
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('CLOTURE', 'Clôturée (entièrement reçue)'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='catalogue.fournisseur')),
                ('site_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_recues', to='core.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_validees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='achats.demandeachat')),
            ],
            options={
                'verbose_name': 'commande fournisseur',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='achats.commandefournisseur')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_creees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réception',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseurLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandefournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='un_produit_par_commande')],
            },
        ),
        migrations.CreateModel(
            name='DemandeAchatLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.demandeachat')),
                ('fournisseur_suggere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_demande', to='catalogue.produit')),
            ],
            options={
                'verbose_name': "ligne de demande d'achat",
                'constraints': [models.UniqueConstraint(fields=('demande', 'produit'), name='un_produit_par_demande')],
            },
        ),
        migrations.CreateModel(
            name='ReceptionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_attendue', models.PositiveIntegerField(default=0)),
                ('quantite_recue', models.PositiveIntegerField(default=0)),
                ('conforme', models.BooleanField(default=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reception', to='catalogue.produit')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.reception')),
            ],
            options={
                'verbose_name': 'ligne de réception',
                'constraints': [models.UniqueConstraint(fields=('reception', 'produit'), name='un_produit_par_reception')],
            },
        ),
    ]
