# Generated by Django 6.0.7 on 2026-07-29 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('catalogue', '0002_categorie_produit'),
        ('core', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='soumis_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='soumis_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions_directes', to='catalogue.fournisseur'),
        ),
        migrations.AddField(
            model_name='reception',
            name='site_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions_directes', to='core.site'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumise'), ('VALIDE', 'Validée'), ('CLOTURE', 'Clôturée (entièrement reçue)'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=12),
        ),
        migrations.AlterField(
            model_name='reception',
            name='commande',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une réception directe (sans bon de commande préalable).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='achats.commandefournisseur'),
        ),
    ]
