# Generated by Django 6.0.7 on 2026-07-30 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_commande_soumis_reception_libre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeachat',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='site',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='valide_n1_par',
        ),
        migrations.RemoveField(
            model_name='demandeachat',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='commandefournisseur',
            name='demande',
        ),
        migrations.RemoveConstraint(
            model_name='demandeachatligne',
            name='un_produit_par_demande',
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='valide_n1_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='valide_n1_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_validees_n1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumise'), ('VALIDE_N1', 'Validée superviseur'), ('VALIDE', 'Validée'), ('CLOTURE', 'Clôturée (entièrement reçue)'), ('REJETE', 'Rejetée'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=12),
        ),
        migrations.AlterField(
            model_name='reception',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='achats.commandefournisseur'),
        ),
        migrations.RemoveField(
            model_name='demandeachatligne',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='demandeachatligne',
            name='fournisseur_suggere',
        ),
        migrations.RemoveField(
            model_name='demandeachatligne',
            name='produit',
        ),
        migrations.DeleteModel(
            name='DemandeAchat',
        ),
        migrations.DeleteModel(
            name='DemandeAchatLigne',
        ),
    ]
