# Generated by Django 6.0.7 on 2026-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_commande_trace_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionligne',
            name='justification_ecart',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
