# Generated by Django 6.0.7 on 2026-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_justification_ecart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandefournisseurligne',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='receptionligne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
