# Generated by Django 6.0.7 on 2026-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_prix_sur_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('CLOTURE', 'Clôturée'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=12),
        ),
    ]
