# Generated by Django 6.0.7 on 2026-07-29 15:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        ('kits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.CharField(editable=False, help_text='Séquentiel par école.', max_length=30)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remise', models.DecimalField(decimal_places=2, default=0, help_text='Remise conventionnelle accordée au personnel administratif.', max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'Payée, à remettre'), ('LIVREE', 'Livrée'), ('PARTIELLE', 'Livrée partiellement'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('livree_le', models.DateTimeField(blank=True, null=True)),
                ('ecole', models.ForeignKey(limit_choices_to={'type': 'ECOLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='core.site')),
                ('livree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to=settings.AUTH_USER_MODEL)),
                ('vendeuse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vente',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='kits.kit')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='catalogue.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'ligne de vente',
            },
        ),
        migrations.CreateModel(
            name='LigneProduitVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_due', models.PositiveIntegerField()),
                ('quantite_servie', models.PositiveIntegerField(default=0, help_text='Quantité effectivement sortie du stock.')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_produit_vente', to='catalogue.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_produit', to='ventes.vente')),
            ],
            options={
                'verbose_name': "besoin produit d'une vente",
                'ordering': ['produit__code'],
            },
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['ecole', 'statut'], name='ventes_vent_ecole_i_5e90cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(fields=('ecole', 'numero'), name='numero_unique_par_ecole'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kit__isnull', False), ('produit__isnull', True)), models.Q(('kit__isnull', True), ('produit__isnull', False)), _connector='OR'), name='ligne_vente_kit_ou_produit_exclusif'),
        ),
        migrations.AddConstraint(
            model_name='ligneproduitvente',
            constraint=models.UniqueConstraint(fields=('vente', 'produit'), name='un_besoin_par_vente_et_produit'),
        ),
    ]
