# Generated by Django 6.0.7 on 2026-07-29 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sequencecompteur_site_code'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('montant_especes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_autre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('cloture_le', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(limit_choices_to={'type': 'ECOLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='clotures', to='core.site')),
            ],
            options={
                'verbose_name': 'clôture de caisse',
                'ordering': ['-date', 'ecole'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'date'), name='une_cloture_par_ecole_et_jour')],
            },
        ),
    ]
