# Generated by Django 6.0.7 on 2026-07-30 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_ligne_vente_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='annulee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annulations_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_annulation',
            field=models.TextField(blank=True),
        ),
    ]
