# Generated by Django 6.0.7 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_annulation_structuree'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='annulation_demandee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_demande',
            field=models.TextField(blank=True),
        ),
    ]
