# Generated by Django 6.0.7 on 2026-08-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_demande_annulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneproduitvente',
            name='avoir_annule',
            field=models.BooleanField(default=False, help_text="L'avoir restant a été annulé — le client est remboursé."),
        ),
        migrations.AddField(
            model_name='ligneproduitvente',
            name='avoir_annule_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligneproduitvente',
            name='avoir_annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneproduitvente',
            name='prix_unitaire_avoir',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix unitaire du produit au moment de la vente, pour valoriser l'avoir.", max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='telephone_client',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone du client — obligatoire quand la vente génère un avoir.', max_length=20),
        ),
    ]
