# Generated by Django 6.0.7 on 2026-08-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_avoir_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
