# Generated by Django 6.0.7 on 2026-07-29 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0006_sequencecompteur_site_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de saisie'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='core.site')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inventaire',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='InventaireLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField(default=0, help_text='Solde calculé au moment de la saisie.')),
                ('quantite_physique', models.IntegerField(default=0, help_text='Quantité comptée physiquement.')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaires.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='catalogue.produit')),
            ],
            options={
                'verbose_name': "ligne d'inventaire",
                'ordering': ['produit__code'],
                'constraints': [models.UniqueConstraint(fields=('inventaire', 'produit'), name='un_produit_par_inventaire')],
            },
        ),
    ]
