# Generated by Django 6.0.7 on 2026-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaireligne',
            name='commentaire',
            field=models.CharField(blank=True, default='', help_text="Explication de l'écart constaté.", max_length=300),
        ),
    ]
