# Generated by Django 6.0.7 on 2026-07-29 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('conditions_paiement', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fournisseur',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'marque',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. C200, ET300GF, TP100.', max_length=20, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('CAHIER', 'Cahier'), ('PETIT_MATERIEL', 'Petit matériel'), ('LIVRE', 'Livre au programme')], default='CAHIER', max_length=20)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('cout_achat', models.DecimalField(decimal_places=2, default=0, help_text="Coût d'achat unitaire de référence, en F CFA. Base du coût de revient des kits.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_detail', models.DecimalField(decimal_places=2, default=0, help_text="Prix de vente à l'unité, en F CFA. Non affiché publiquement (section 7.7).", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.marque')),
            ],
            options={
                'verbose_name': 'produit',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('delai_livraison_jours', models.PositiveIntegerField(default=7)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='catalogue.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'offre fournisseur',
                'constraints': [models.UniqueConstraint(fields=('produit', 'fournisseur'), name='offre_unique_par_couple')],
            },
        ),
    ]
