# Generated by Django 6.0.7 on 2026-08-07 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0009_alter_site_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_detail', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_produits', to='core.site')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_ecoles', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'prix école',
                'constraints': [models.UniqueConstraint(fields=('produit', 'ecole'), name='prix_unique_par_produit_et_ecole')],
            },
        ),
    ]
