# Generated by Django 6.0.7 on 2026-07-30 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_categorie_produit'),
        ('core', '0008_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('LIVREE', 'Livrée — en attente de réception'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('livree_le', models.DateTimeField(blank=True, null=True)),
                ('recue_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecole_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(limit_choices_to={'type': 'ECOLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecole', to='core.site')),
                ('livree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecole_livrees', to=settings.AUTH_USER_MODEL)),
                ('recue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_ecole_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande école',
                'verbose_name_plural': 'commandes école',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommandeEcoleLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantite_livree', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite_recue', models.PositiveIntegerField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.commandeecole')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande_ecole', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'ligne de commande école',
                'verbose_name_plural': 'lignes de commande école',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='un_produit_par_commande_ecole')],
            },
        ),
        migrations.CreateModel(
            name='StockReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='approvisionnement.commandeecole')),
                ('ecole', models.ForeignKey(limit_choices_to={'type': 'ECOLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_reserves_ecole', to='core.site')),
                ('magasin', models.ForeignKey(limit_choices_to={'type': 'MAGASIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_reserves', to='core.site')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'stock réservé',
                'verbose_name_plural': 'stocks réservés',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='une_reservation_par_commande_produit')],
            },
        ),
    ]
