# Generated by Django 6.0.7 on 2026-07-31 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0001_initial'),
        ('catalogue', '0002_categorie_produit'),
        ('core', '0009_alter_site_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('LIVREE', 'Livrée — en transit'), ('RECUE', 'Reçue'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=12)),
                ('observations', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('soumise_le', models.DateTimeField(blank=True, null=True)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('livree_le', models.DateTimeField(blank=True, null=True)),
                ('recue_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.CharField(blank=True, max_length=500)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_creees', to=settings.AUTH_USER_MODEL)),
                ('livree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_livrees', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(limit_choices_to={'type': 'MAGASIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin', to='core.site')),
                ('recue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_recues', to=settings.AUTH_USER_MODEL)),
                ('soumise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_soumises', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'commande magasin',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommandeMagasinLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantite_livree', models.PositiveIntegerField(blank=True, null=True)),
                ('quantite_recue', models.PositiveIntegerField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='approvisionnement.commandemagasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande_magasin', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'ligne de commande magasin',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='un_produit_par_commande_magasin')],
            },
        ),
    ]
