# Generated by Django 6.0.7 on 2026-07-31 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0002_commande_magasin'),
        ('catalogue', '0002_categorie_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemagasin',
            name='rejete_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandemagasin',
            name='rejete_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_magasin_rejetees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockReserveDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_depot', to='approvisionnement.commandemagasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_depot', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'stock réservé dépôt',
                'verbose_name_plural': 'stocks réservés dépôt',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='une_reservation_depot_par_commande_produit')],
            },
        ),
    ]
