# Generated by Django 6.0.7 on 2026-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0003_stock_reserve_depot_et_rejete_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemagasinligne',
            name='motif_ecart',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
