# Generated by Django 6.0.7 on 2026-08-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0005_commande_ecole_workflow_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemagasinligne',
            name='quantite_deja_recue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
