# Generated by Django 6.0.7 on 2026-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0006_commande_magasin_ligne_quantite_deja_recue'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemagasin',
            name='livraison_close',
            field=models.BooleanField(default=False),
        ),
    ]
