# Generated by Django 6.0.7 on 2026-08-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0007_commande_magasin_livraison_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemagasinligne',
            name='quantite_deja_livree',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
