# Generated by Django 6.0.7 on 2026-08-14 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0008_quantite_deja_livree'),
        ('core', '0014_numero_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecole',
            name='numero_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandemagasin',
            name='numero_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='commandeecole',
            constraint=models.UniqueConstraint(fields=('ecole', 'numero_local'), name='numero_local_unique_ecole'),
        ),
        migrations.AddConstraint(
            model_name='commandemagasin',
            constraint=models.UniqueConstraint(fields=('magasin', 'numero_local'), name='numero_local_unique_magasin'),
        ),
    ]
