# Generated by Django 6.0.7 on 2026-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0009_numero_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecole',
            name='livraison_close',
            field=models.BooleanField(default=False),
        ),
    ]
