# Generated by Django 6.0.7 on 2026-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvisionnement', '0010_livraison_close_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeecoleligne',
            name='quantite_deja_livree',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commandeecoleligne',
            name='quantite_deja_recue',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
