# Generated by Django 6.0.7 on 2026-07-29 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIVRAISON', 'Livraison non conforme'), ('PRODUIT', 'Défaut produit'), ('PROCESSUS', 'Non-conformité processus'), ('STOCK', 'Écart de stock'), ('AUTRE', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours de traitement'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('reference_document', models.CharField(blank=True, max_length=100)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites_cloturees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites_creees', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformites', to='core.site')),
            ],
            options={
                'verbose_name': 'non-conformité',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ActionCorrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_correctives', to=settings.AUTH_USER_MODEL)),
                ('non_conformite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='nonconformites.nonconformite')),
            ],
            options={
                'verbose_name': 'action corrective',
                'ordering': ['cree_le'],
            },
        ),
    ]
