# Generated by Django 6.0.7 on 2026-08-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformites', '0003_nonconformite_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformite',
            name='type',
            field=models.CharField(choices=[('PRODUIT', 'Défaut produit'), ('PROCESSUS', 'Non-conformité processus'), ('FRAUDE', 'Fraude'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
